version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vntmtool_app # Đặt tên container cho dễ quản lý
    env_file:
      - .env # Nạp biến môi trường từ file .env
    volumes:

      - ./media_root:/app/media_root
      - ./logs:/app/logs
      - ./scraper_control_state.json:/app/scraper_control_state.json
      - ./scraper_page_state.json:/app/scraper_page_state.json


    depends_on:
      db: # Ứng dụng phụ thuộc vào database
        condition: service_healthy # Chờ database sẵn sàng (cần healthcheck trong service db)
    networks:
      - vntmtool_network
    # Lệnh chạy mặc định sẽ được kế thừa từ CMD trong Dockerfile
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: vntmtool_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map cổng để có thể truy cập DB từ bên ngoài (ví dụ: pgAdmin)
    networks:
      - vntmtool_network
    healthcheck: # Kiểm tra sức khỏe của database
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
networks:
  vntmtool_network:
    driver: bridge